export interface OpenSourceComponent {
  name: string
  version: string
  license: string
  copyright: string
  url: string
  purpose: string
}

export const openSourceComponents: OpenSourceComponent[] = [
  {
    name: 'Vue.js',
    version: '3.5.41',
    license: 'MIT',
    copyright: 'Copyright (c) 2018-present, Yuxi (Evan) You',
    url: 'https://github.com/vuejs/core',
    purpose: '用户界面框架及其运行时组件',
  },
  {
    name: 'Vue Router',
    version: '4.6.4',
    license: 'MIT',
    copyright: 'Copyright (c) 2019-present Eduardo San Martin Morote',
    url: 'https://github.com/vuejs/router',
    purpose: '页面路由',
  },
  {
    name: 'Vue DevTools API',
    version: '6.6.4 / 7.7.10',
    license: 'MIT',
    copyright: 'Copyright (c) Guillaume Chau and contributors; 7.x Copyright (c) 2023 webfansplz',
    url: 'https://github.com/vuejs/devtools',
    purpose: 'Vue Router 与 Pinia 的调试接口依赖',
  },
  {
    name: 'Pinia',
    version: '3.0.4',
    license: 'MIT',
    copyright: 'Copyright (c) 2019-present Eduardo San Martin Morote',
    url: 'https://github.com/vuejs/pinia',
    purpose: '应用状态管理',
  },
  {
    name: 'Ionic Framework',
    version: '8.8.18',
    license: 'MIT',
    copyright: 'Copyright 2015-present Drifty Co.',
    url: 'https://github.com/ionic-team/ionic-framework',
    purpose: '移动端界面组件与 Vue 集成',
  },
  {
    name: 'Stencil',
    version: '4.43.5 / 4.44.0',
    license: 'MIT',
    copyright: 'Copyright (c) 2019-present Drifty Co.',
    url: 'https://github.com/ionic-team/stencil',
    purpose: 'Ionic Web Components 运行时',
  },
  {
    name: 'Stencil Vue Output Target',
    version: '0.10.7',
    license: 'MIT',
    copyright: 'Copyright (c) 2019-present Drifty Co.',
    url: 'https://github.com/ionic-team/stencil-ds-output-targets',
    purpose: 'Ionic 的 Vue 组件绑定',
  },
  {
    name: 'Ionicons',
    version: '8.1.0',
    license: 'MIT',
    copyright: 'Copyright (c) 2015-present Ionic',
    url: 'https://github.com/ionic-team/ionicons',
    purpose: 'Ionic 图标运行时',
  },
  {
    name: 'Capacitor',
    version: '8.5.0',
    license: 'MIT',
    copyright: 'Copyright (c) 2017-present Drifty Co.',
    url: 'https://github.com/ionic-team/capacitor',
    purpose: 'Web 与 Android 原生能力桥接',
  },
  {
    name: 'Capacitor 官方插件（App、Filesystem、Haptics、Share、Status Bar）',
    version: '8.0.1–8.1.2',
    license: 'MIT',
    copyright: 'Copyright 2020-present Ionic；Filesystem: Copyright (c) 2025 Ionic',
    url: 'https://github.com/ionic-team/capacitor-plugins',
    purpose: '应用状态、文件、触感、分享和状态栏能力',
  },
  {
    name: 'Capacitor Synapse',
    version: '1.0.4',
    license: 'MIT（随包许可证文件）',
    copyright: 'Copyright (c) 2025 Ionic',
    url: 'https://github.com/ionic-team/capacitor',
    purpose: 'Capacitor Filesystem 的原生接口支持',
  },
  {
    name: 'tslib',
    version: '2.8.1',
    license: '0BSD',
    copyright: 'Copyright (c) Microsoft Corporation.',
    url: 'https://github.com/microsoft/tslib',
    purpose: 'TypeScript 运行时辅助函数',
  },
  {
    name: 'Capacitor Community SQLite',
    version: '8.1.1',
    license: 'MIT',
    copyright: 'Copyright (c) 2020-2024 Quéau Jean Pierre',
    url: 'https://github.com/capacitor-community/sqlite',
    purpose: '本地 SQLite 数据库桥接',
  },
  {
    name: 'jeep-sqlite',
    version: '2.8.0',
    license: 'MIT',
    copyright: 'Copyright (c) 2018 Jean Pierre Quéau',
    url: 'https://github.com/jepiqueau/jeep-sqlite',
    purpose: 'SQLite 插件的 Web 组件依赖',
  },
  {
    name: 'SheetJS Community Edition',
    version: '0.20.3',
    license: 'Apache-2.0',
    copyright: 'Copyright (C) 2012-present SheetJS LLC',
    url: 'https://git.sheetjs.com/SheetJS/sheetjs',
    purpose: '读取 XLSX 题库文件',
  },
  {
    name: 'browser-fs-access',
    version: '0.35.0',
    license: 'Apache-2.0',
    copyright: 'Authored by Thomas Steiner / GoogleChromeLabs',
    url: 'https://github.com/GoogleChromeLabs/browser-fs-access',
    purpose: 'jeep-sqlite 的浏览器文件访问依赖',
  },
  {
    name: 'localForage',
    version: '1.10.0',
    license: 'Apache-2.0',
    copyright: 'Copyright 2014 Mozilla',
    url: 'https://github.com/localForage/localForage',
    purpose: 'jeep-sqlite 的浏览器存储依赖',
  },
  {
    name: 'sql.js',
    version: '1.14.1',
    license: 'MIT',
    copyright: 'Copyright (c) 2017 sql.js authors',
    url: 'https://github.com/sql-js/sql.js',
    purpose: 'jeep-sqlite 的 WebAssembly SQLite 依赖',
  },
  {
    name: 'JSZip',
    version: '3.10.1',
    license: 'MIT（从 MIT / GPL-3.0-or-later 双许可中选择）',
    copyright: 'Copyright (c) 2009-2016 Stuart Knightley, David Duponchel, Franz Buchinger, António Afonso',
    url: 'https://github.com/Stuk/jszip',
    purpose: 'jeep-sqlite 的压缩文件处理依赖',
  },
  {
    name: 'pako',
    version: '1.0.11',
    license: 'MIT AND Zlib',
    copyright: 'Copyright (C) 2014-2017 Vitaly Puzrin and Andrei Tuputcyn',
    url: 'https://github.com/nodeca/pako',
    purpose: 'JSZip 的压缩算法依赖',
  },
  {
    name: 'lie',
    version: '3.1.1 / 3.3.0',
    license: 'MIT',
    copyright: 'Copyright (c) 2014-2018 Calvin Metcalf, Jordan Harband',
    url: 'https://github.com/calvinmetcalf/lie',
    purpose: 'Promise 兼容层',
  },
  {
    name: 'readable-stream',
    version: '2.3.8',
    license: 'MIT',
    copyright: 'Copyright Node.js contributors. All rights reserved.',
    url: 'https://github.com/nodejs/readable-stream',
    purpose: 'JSZip 的流处理依赖',
  },
  {
    name: 'core-util-is',
    version: '1.0.3',
    license: 'MIT',
    copyright: 'Copyright Node.js contributors. All rights reserved.',
    url: 'https://github.com/isaacs/core-util-is',
    purpose: 'readable-stream 的运行时依赖',
  },
  {
    name: 'immediate',
    version: '3.0.6',
    license: 'MIT',
    copyright: 'Copyright (c) 2012 Barnesandnoble.com, Donavon West, Domenic Denicola, Brian Cavalier',
    url: 'https://github.com/calvinmetcalf/immediate',
    purpose: 'lie 的任务调度依赖',
  },
  {
    name: 'inherits',
    version: '2.0.4',
    license: 'ISC',
    copyright: 'Copyright (c) Isaac Z. Schlueter',
    url: 'https://github.com/isaacs/inherits',
    purpose: 'readable-stream 的继承辅助依赖',
  },
  {
    name: 'isarray',
    version: '1.0.0',
    license: 'MIT',
    copyright: 'Copyright (c) 2013 Julian Gruber',
    url: 'https://github.com/juliangruber/isarray',
    purpose: 'readable-stream 的类型判断依赖',
  },
  {
    name: 'process-nextick-args',
    version: '2.0.1',
    license: 'MIT',
    copyright: 'Copyright (c) 2015 Calvin Metcalf',
    url: 'https://github.com/calvinmetcalf/process-nextick-args',
    purpose: 'readable-stream 的异步调度依赖',
  },
  {
    name: 'safe-buffer',
    version: '5.1.2',
    license: 'MIT',
    copyright: 'Copyright (c) Feross Aboukhadijeh',
    url: 'https://github.com/feross/safe-buffer',
    purpose: 'readable-stream 的缓冲区兼容依赖',
  },
  {
    name: 'string_decoder',
    version: '1.1.1',
    license: 'MIT',
    copyright: 'Copyright Node.js contributors. All rights reserved.',
    url: 'https://github.com/nodejs/string_decoder',
    purpose: 'readable-stream 的字符串解码依赖',
  },
  {
    name: 'setimmediate',
    version: '1.0.5',
    license: 'MIT',
    copyright: 'Copyright (c) 2012 Barnesandnoble.com, Donavon West, Domenic Denicola',
    url: 'https://github.com/YuzuJS/setImmediate',
    purpose: 'JSZip 的任务调度依赖',
  },
  {
    name: 'util-deprecate',
    version: '1.0.2',
    license: 'MIT',
    copyright: 'Copyright (c) 2014 Nathan Rajlich',
    url: 'https://github.com/TooTallNate/util-deprecate',
    purpose: 'readable-stream 的兼容依赖',
  },
  {
    name: 'ionfilesystem-android',
    version: '1.1.0',
    license: 'MIT',
    copyright: 'Copyright (c) 2025 Ionic',
    url: 'https://github.com/ionic-team/ion-android-filesystem',
    purpose: 'Android 文件系统原生实现',
  },
  {
    name: 'SQLCipher for Android',
    version: '4.17.0',
    license: 'BSD-3-Clause',
    copyright: 'Copyright (c) 2008-2023 ZETETIC LLC. All rights reserved.',
    url: 'https://github.com/sqlcipher/sqlcipher-android',
    purpose: 'Android SQLite 加密实现',
  },
  {
    name: 'SQLite',
    version: '由 SQLCipher / AndroidX 提供',
    license: 'Public Domain',
    copyright: 'SQLite 源代码已由作者奉献给公共领域',
    url: 'https://www.sqlite.org/copyright.html',
    purpose: '嵌入式数据库引擎',
  },
  {
    name: 'LibTomCrypt',
    version: '由 SQLCipher 提供',
    license: 'Unlicense / Public Domain',
    copyright: 'The LibTomCrypt project and contributors',
    url: 'https://github.com/libtom/libtomcrypt',
    purpose: 'SQLCipher 默认密码学后端',
  },
  {
    name: 'AndroidX',
    version: '随当前 Android 依赖图锁定',
    license: 'Apache-2.0',
    copyright: 'Copyright The Android Open Source Project',
    url: 'https://github.com/androidx/androidx',
    purpose: 'Android UI、Room、SQLite、安全和生物识别支持库',
  },
  {
    name: 'Apache Cordova Android',
    version: '14.0.1',
    license: 'Apache-2.0',
    copyright: 'Copyright The Apache Software Foundation',
    url: 'https://github.com/apache/cordova-android',
    purpose: 'Capacitor Android 的 Cordova 兼容层',
  },
  {
    name: 'Kotlin Standard Library / kotlinx.coroutines',
    version: '随当前 Android 依赖图锁定',
    license: 'Apache-2.0',
    copyright: 'Copyright JetBrains s.r.o. and Kotlin contributors',
    url: 'https://github.com/Kotlin/kotlinx.coroutines',
    purpose: 'Android 原生代码运行时与协程支持',
  },
]
